name: Go Vulnerability Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1
        with:
          repo-checkout: false
          go-version-file: go.mod
          go-package: ./...
